### ISSUE TITLE
ui missing

### ISSUE THREAD

**Issue by Axel-Erfurt** [Houston4444/Patchance#6]
```
axel@chieftech:/tmp/Patchance$ ./src/patchance.py
Traceback (most recent call last):
  File "/tmp/Patchance/./src/patchance.py", line 46, in <module>
    from main_win import MainWindow
  File "/tmp/Patchance/src/main_win.py", line 8, in <module>
    from about_dialog import AboutDialog
  File "/tmp/Patchance/src/about_dialog.py", line 3, in <module>
    from ui.about_patchance import Ui_DialogAboutPatchance
ModuleNotFoundError: No module named 'ui'

```

**Comment by Houston4444** [comment]
Hi.

the magic word is 
`make`
